name: Azure Python 3.10
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        make install-azure
    - name: Lint source code with Pylint
      run: |
        make lint
    - name: Run tests using Pytest
      run: |
        make test
    # Skip formatting step as Black is not installed in Azure
    # - name: Format source code with Black
    #   run: |
    #     make format
