name: GCP Python 3.11
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        make install
    - name: Lint source code with Pylint
      run: |
        make lint
    - name: Run tests using Pytest
      run: |
        make test
    - name: Format source code with Black
      run: |
        make format
